services:
  db:
    image: magsxl09/db-postgres:1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eduvue
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
  backend:
    image: magsxl09/backend:1
    working_dir: /src
    volumes:
      - ./backend/EduVue.Api:/src
    command: sh -c "dotnet restore && dotnet watch run --urls http://0.0.0.0:5001"
    depends_on:
      - db
    environment:
      ConnectionStrings__Default: Host=db;Port=5432;Username=postgres;Password=postgres;Database=eduvue
    ports:
      - '5001:5001'
  frontend:
    image: magsxl09/frontend:1
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 3000"
    depends_on:
      - backend
    ports:
      - '3000:3000'
  mobile:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./mobile:/app
      - /app/node_modules
    command: sh -c "npm install -g @expo/ngrok@^4.1.0 && npm install --legacy-peer-deps && EXPO_NONINTERACTIVE=1 npx expo start --tunnel"
    depends_on:
      - backend
    ports:
      - '19000:19000'
      - '19001:19001'
